# Generated by Django 6.0.1 on 2026-01-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=65)),
                ('product_sku', models.CharField(max_length=65, unique=True)),
                ('product_price', models.FloatField()),
                ('product_quantity', models.IntegerField()),
            ],
        ),
    ]
